// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShelter.Models;

namespace PetShelter.Migrations
{
    [DbContext(typeof(PetShelterContext))]
    [Migration("20200612173102_SeedData2")]
    partial class SeedData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PetShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Admitted");

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Admitted = new DateTime(2019, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 6,
                            Breed = "American Shorthair",
                            Name = "Macavity",
                            Notes = "A mystery cat, a master criminal who can defy the law."
                        },
                        new
                        {
                            CatId = 2,
                            Admitted = new DateTime(1978, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 42,
                            Breed = "American Shorthair",
                            Name = "Garfield",
                            Notes = "Likes lasagna and summoning eldritch monstrosities."
                        },
                        new
                        {
                            CatId = 3,
                            Admitted = new DateTime(2015, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 9,
                            Breed = "Siamese",
                            Name = "Grumpy Cat",
                            Notes = "Special needs! Also fairly pessimistic."
                        },
                        new
                        {
                            CatId = 4,
                            Admitted = new DateTime(2020, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 3,
                            Breed = "Russian Grey",
                            Name = "Pusheen",
                            Notes = "Needs a diet, surprisingly agile."
                        });
                });

            modelBuilder.Entity("PetShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Admitted");

                    b.Property<int>("Age");

                    b.Property<string>("Breed");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Admitted = new DateTime(2019, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 4,
                            Breed = "Terrier Mutt",
                            Name = "Doggo",
                            Notes = "Who's a good doggo? Doggo is a good doggo!"
                        },
                        new
                        {
                            DogId = 2,
                            Admitted = new DateTime(2020, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 1,
                            Breed = "Shepherd/Lab Mix",
                            Name = "Pupper",
                            Notes = "Just a little pupperino."
                        },
                        new
                        {
                            DogId = 3,
                            Admitted = new DateTime(2018, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 10,
                            Breed = "Pug",
                            Name = "The Right Honorable Charles Beauregard, Esq.",
                            Notes = "Mr. Beauregard takes his tea with a smidge of cream and usually has a constitutional cigar after dinner."
                        },
                        new
                        {
                            DogId = 4,
                            Admitted = new DateTime(2015, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 2,
                            Breed = "West Highland Terrier",
                            Name = "Buddy",
                            Notes = "A real big jerk."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
